config/routes.rb
GSetter::Application.routes.draw do

  resources :users
  resource  :session, only: ["new", "create", "destroy"]

  resources :goals do
    resources :cheers, only: ["create"]
  end

end

app/models/cheer.rb
class Cheer < ActiveRecord::Base
  attr_accessible :goal_id, :user_id

  validate :within_limit

  belongs_to(
    :user,
    class_name: 'User',
    foreign_key: :user_id,
    primary_key: :id
  )

  belongs_to(
    :goal,
    class_name: 'Goal',
    foreign_key: :goal_id,
    primary_key: :id
  )

  def within_limit
    user = User.find(self.user_id)
    if user.cheers.today.count >= 5
      errors.add(:base, "You're out of Cheers! :-(")
    end
  end
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  attr_accessible :body, :status, :user_id, :completed

  validates :body, :status, :user_id, presence: true

  belongs_to(
  :user,
  class_name: "User",
  foreign_key: :user_id,
  primary_key: :id)
  
  has_many(
    :cheers,
    class_name: 'Cheer',
    foreign_key: :goal_id,
    primary_key: :id
  )

end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  attr_accessible :password, :username
  attr_reader :password

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_digest, presence: true

  has_many(
  :goals,
  class_name: "Goal",
  foreign_key: :user_id,
  primary_key: :id)

  has_many(
    :cheers,
    class_name: 'Cheer',
    foreign_key: :user_id,
    primary_key: :id
  ) do
      def today
        where(:created_at => (Time.now.beginning_of_day..Time.now))
      end
  end

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    if user && user.is_password?(password)
      return user
    else
      return nil
    end

  end

  def reset_token
    self.update_attribute(:token, SecureRandom::urlsafe_base64(16))
    self.save
    self.token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(@password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper

  before_filter :authenticate

end

app/controllers/cheers_controller.rb
class CheersController < ApplicationController

  def create
    params[:cheer] = {}
    params[:cheer][:user_id] = current_user.id
    params[:cheer][:goal_id] = params[:goal_id]
    cheer = Cheer.new(params[:cheer])

    if cheer.save
      redirect_to user_url(cheer.goal.user)
    else
      flash[:errors] = cheer.errors.full_messages
      redirect_to user_url(cheer.goal.user)
    end
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def new
    @goal = Goal.new
  end

  def create
    params[:goal][:user_id] = current_user.id
    @goal = Goal.new(params[:goal])

    if @goal.save
      redirect_to current_user
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update_attributes(params[:goal])
      redirect_to current_user
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def destroy
    Goal.destroy(params[:id])
    redirect_to current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_filter :authenticate, only: [:new, :create]

  def new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username], params[:user][:password])

    if @user
      login(@user)
      redirect_to users_url
    else
      flash.now[:errors] = ["Invalid Username/Password Combination"]
      render :new
    end
  end

  def destroy
    @user = current_user
    @user.reset_token
    session[:token] = nil
    render :new
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :authenticate, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      login(@user)
      redirect_to users_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cheers_helper.rb
module CheersHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    return nil unless session[:token]
    @current_user ||= User.find_by_token(session[:token])
  end

  def login(user)
    session[:token] = user.reset_token
  end

  def authenticate
    redirect_to new_session_url unless current_user
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/_form.html.erb
  <form action="<%= action %>" method="post" accept-charset="utf-8">
    <input type="hidden"
           name="authenticity_token"
          value="<%= form_authenticity_token %>">

    <input type="hidden"
           name="_method"
          value="<%= method %>">

    <label>Goal
      <input type="text" name="goal[body]" value="<%= goal.body %>">
    </label>

    <label for="public">Public</label>
    <input type="radio" name="goal[status]" value="public" id="public" <%= "checked".html_safe if goal.status == "public" %>>

    <label for="private">Private</label>
    <input type="radio" name="goal[status]" value="private" id="private" <%= "checked".html_safe if goal.status == "private" %>>

    <p><input type="submit" value="<%= submit %>"></p>
  </form>

app/views/goals/edit.html.erb
<h1>Edit Goal</h1>

<%= render "form", goal: @goal, action: goal_url(@goal.id), method: "put", submit: "Edit Goal" %>

app/views/goals/new.html.erb
<h1>Create Goal</h1>

<%= render "form", goal: @goal, action: goals_url, method: "post", submit: "Create Goal" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GSetter</title>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if flash.now[:errors] && !flash.now[:errors].empty? %>
    <% flash.now[:errors].each do |error| %>
      <%= error %>
    <% end %>
  <% end %>

  <% if current_user %>
    <%= button_to "Logout", session_url, method: :delete %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/shared/_form.html.erb
<form action="<%= action %>" method="post">
  <input type="hidden"
         name="authenticity_token"
        value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input type="text" name="user[username]" id="user_username">

  <label for="password">Password</label>
  <input type="password" name="user[password]" id="password">

  <input type="submit" value="<%= button %>">

</form>

app/views/users/index.html.erb
<h1>Home</h1>


<% @users.each do |user| %>
  <p><%= link_to user.username, user_url(user)%></p>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render "shared/form", action: users_url, button: "Create User" %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<% @user.goals.each do |goal| %>
  <p>
    <% if goal.status == 'public' && @user != current_user %>
      <%= button_to "Cheer!", goal_cheers_url(goal), method: :post %>
    <% end %>

    <% if goal.cheers.count == 1 %>
      <%= '1 Cheer!'%>
    <% elsif goal.cheers.count > 1 %>
      <%= goal.cheers.count %> Cheers!
    <% end %>
    <%= goal.body if goal.status == 'public' %>
    <%= goal.body if @user == current_user && goal.status == 'private' %><%= " - Completed".html_safe if goal.completed %>

    <% if @user == current_user %>
      <form action="<%= goal_url(goal.id) %>" method="post">
        <input type="hidden"
               name="authenticity_token"
              value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="put">
        <input type="hidden" name="goal[completed]" value="1">
        <p><input type="submit" value="Completed"></p>
      </form>
      <%= link_to "Edit Goal", edit_goal_url(goal) %>
      <%= button_to "Delete", goal, method: :delete %>
    <% end %>
  </p>
<% end %>


<% if @user == current_user %>
  <%= link_to "New Goal", new_goal_url %>
<% end %>